/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    
    public static void main(String[] args) {
        DishStack stack = new DishStack();
        Dish oneDish = new Dish("A dish with one fish pattern on it");
        Dish twoDish = new Dish("A dish with two fish patterns on it");
        Dish redDish = new Dish("A dish with a red fish pattern on it");
        Dish blueDish = new Dish("A dish with a blue fish pattern on it");
        
        // The variable stack_size should equal zero.
        int stackSize = stack.size();

        System.out.println(stackSize);
        
        stack.push(oneDish);
        stack.push(twoDish);
        stack.push(redDish);
        stack.push(blueDish);
        
        // The variable sizeAfterPushes should equal four.
        int sizeAfterPushes = stack.size();
        
        // The variable peekedDish should have a description of "A dish with a blue fish pattern on it"
        Dish peekedDish = stack.peek();
        
        // The variable poppedDish should have a description of "A dish with a blue fish pattern on it"
        Dish poppedDish = stack.pop();

        int sizeAfterpop = stack.size();

        System.out.println(sizeAfterpop);
        
        // The variable anotherPoppedDish should have a description of "A dish with a red fish pattern on it"
        Dish anotherPoppedDish = stack.pop();
        
        // The variable finalSize should equal two.
        int finalSize = stack.size();

        stack.printStack();

        System.out.println(finalSize);

        stack.clearStack();

        System.out.println(stack.size()); //should be 0


    }
}
